language: node_js
node_js:
  - "0.8"

install:
  - "alias sudo='sudo env PATH=$PATH $@'"
  - "bash scripts/install_xtuple.sh -ipn"

before_script:
  - "cd node-datasource"
  - "sudo env PATH=$PATH node main.js &"
  - "sleep 10"
  - "cd .."

script:
  - "npm run-script test"
